services:
    pythonru:
      environment:
        AIRBRAKE_API_KEY: 04d5aa306d86308307ed1c5b43d63a0b
        AWS_ACCESS_KEY_ID: AKIAJB5ZVEMHT4ET2RUA
        AWS_SECRET_ACCESS_KEY: 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
        AWS_STORAGE_BUCKET_NAME: moscowdjango
        CLOUDAMQP_URL: redis://redis:6379
        DATABASE_URL: postgres://mskpython:a70ea3f1bc1474920d3c9477@dev.python.ru:5432/moscowpython
        DJANGO_SETTINGS_MODULE: moscowdjango.settings_production
        DOMAIN: www.moscowpython.ru
        EMBEDLY_KEY: 71fcde24acea11e1a3424040aae4d8c9
        NEW_RELIC_APP_NAME: moscowdjango
        NEW_RELIC_ID: 139813
        NEW_RELIC_LICENSE_KEY: f6bf05515f2ba4900801e52ddf2ce5fecb082967
        NEW_RELIC_LOG: stdout
        PAPERTRAIL_API_TOKEN: elLOUpdBaQg1D8R6nij9
        REDISCLOUD_URL: redis://redis:6379
        SECRET_KEY: dffhkf347hf7ddh2d
        TIMEPAD_API_KEY: 11fcefd0a0e7680b7cebaa5cb14bac66
        TIMEPAD_MAILLIST_ID: 15134
        TIMEPAD_ORG_ID: 5899
        DEBUG: 1
      image: korneevm/moscowpython
      ports:
      - 8000:8000
version: '3.5'