[tool.black]
line-length = 120
skip-string-normalization = true
skip-magic-trailing-comma = true
exclude = '''
/(
    \.git
  | \.mypy_cache
  | env
  | venv
  | migrations
)/
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
ensure_newline_before_comments = true
use_parentheses = true
add_imports = ['from __future__ import annotations']
skip_gitignore = true
skip = ['migrations']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "moscowdjango.settings"
DJANGO_CONFIGURATION = "Test"
testpaths = "apps"
addopts = [
    "--nomigrations",
]