name: Duild and deploy Docker container
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
      DJANGO_DB_NAME: postgres
      DJANGO_CONFIGURATION: Test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{env.DJANGO_DB_USER}}
          POSTGRES_PASSWORD: ${{env.DJANGO_DB_PASSWORD}}
          POSTGRES_DB: ${{env.DJANGO_DB_NAME}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements/base.txt
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag korneevm/moscowpython
    - name: Push the tagged Docker image
      run: docker push korneevm/moscowpython
    - name: login to server and pull container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd /opt/servers
          docker-compose pull moscowpython
          docker-compose up -d
          docker exec -i servers_moscowpython_1 python3 manage.py collectstatic --noinput
